name: Black Code Formatting Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
  push:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  black-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    - name: Check code formatting with black
      run: |
        black --check --diff .